# Generated by Django 2.2.7 on 2021-05-30 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='book',
            name='phone_number',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='services',
            field=models.CharField(choices=[('nn', 'Без услуг'), ('ph', 'Фотограф'), ('st', 'Оборудование')], default='nn', max_length=2),
        ),
    ]
