# Generated by Django 2.2.7 on 2021-05-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_auto_20210530_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.CharField(choices=[('10:30', '10:30'), ('12:30', '12:30'), ('15:00', '15:00')], default='10', max_length=2),
        ),
    ]
