# Generated by Django 2.2.7 on 2021-05-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0004_auto_20210530_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='time',
            field=models.CharField(choices=[('10:00', '10:00'), ('12:30', '12:30'), ('15:00', '15:00')], default='10:00', max_length=5, unique_for_date='date'),
        ),
    ]
