# Generated by Django 2.2.7 on 2021-05-30 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0006_booksss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
