# Generated by Django 2.2.7 on 2021-05-30 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0007_delete_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booksss',
            new_name='Book',
        ),
    ]
